export const AUTH = {
  REQUEST: "AUTH_REQUEST",
  ERROR: "AUTH_ERROR",
  SUCCESS: "AUTH_SUCCESS",

  GETME: {
    REQUEST: "AUTH_GETME_REQUEST",
    ERROR: "AUTH_GETME_ERROR",
    SUCCESS: "AUTH_GETME_SUCCESS"
  }
};

export const REGISTER = {
  REQUEST: "REGISTER_REQUEST",
  ERROR: "REGISTER_ERROR",
  SUCCESS: "REGISTER_SUCCESS"
};

export const SERVERS_LIST = {
  REQUEST: "SERVERS_LIST_REQUEST",
  ERROR: "SERVERS_LIST_ERROR",
  SUCCESS: "SERVERS_LIST_SUCCESS"
};

export const SERVER_CREATION = {
  REQUEST: "SERVER_CREATION_REQUEST",
  ERROR: "SERVER_CREATION_ERROR",
  SUCCESS: "SERVER_CREATION_SUCCESS"
};

export const SERVER_DELETE = {
  REQUEST: "SERVER_DELETE_REQUEST",
  ERROR: "SERVER_DELETE_ERROR",
  SUCCESS: "SERVER_DELETE_SUCCESS"
};

export const SERVER_BY_ID = {
  REQUEST: "SERVER_BY_ID_REQUEST",
  ERROR: "SERVER_BY_ID_ERROR",
  SUCCESS: "SERVER_BY_ID_SUCCESS"
};

export const SERVER_KEY_GET = {
  REQUEST: "SERVER_KEY_GET_REQUEST",
  ERROR: "SERVER_KEY_GET_ERROR",
  SUCCESS: "SERVER_KEY_GET_SUCCESS"
};

export const SERVER_KEY_CREATE = {
  REQUEST: "SERVER_KEY_CREATE_REQUEST",
  ERROR: "SERVER_KEY_CREATE_ERROR",
  SUCCESS: "SERVER_KEY_CREATE_SUCCESS"
};

export const NOTIFY = {
  LOADING: "NOTIFY_LOADING",
  ERROR: "NOTIFY_ERROR",
  SUCCESS: "NOTIFY_SUCCESS",
  INFO: "NOTIFY_INFO",
  DESTROY: "NOTIFY_DESTROY"
};

export const SERVICE = {
  CREATE: {
    REQUEST: "SERVICE_CREATE_REQUEST",
    SUCCESS: "SERVICE_CREATE_SUCCESS",
    ERROR: "SERVICE_CREATE_ERROR"
  },
  LIST: {
    REQUEST: "SERVICE_LIST_REQUEST",
    SUCCESS: "SERVICE_LIST_SUCCESS",
    ERROR: "SERVICE_LIST_ERROR"
  },
  REMOVE: {
    REQUEST: "SERVICE_REMOVE_REQUEST",
    SUCCESS: "SERVICE_REMOVE_SUCCESS",
    ERROR: "SERVICE_REMOVE_ERROR"
  },
  EDIT: {
    REQUEST: "SERVICE_EDIT_REQUEST",
    SUCCESS: "SERVICE_EDIT_SUCCESS",
    ERROR: "SERVICE_EDIT_ERROR"
  }
};

export const DEPENDENCIES = {
  CREATE: {
    REQUEST: "DEPENDENCIES_CREATE_REQUEST",
    SUCCESS: "DEPENDENCIES_CREATE_SUCCESS",
    ERROR: "DEPENDENCIES_CREATE_ERROR"
  },
  GET: {
    REQUEST: "DEPENDENCIES_GET_REQUEST",
    SUCCESS: "DEPENDENCIES_GET_SUCCESS",
    ERROR: "DEPENDENCIES_GET_ERROR"
  }
};
